name: RunsafeWorldGuardBridge
main: no.runsafe.worldguardbridge.WorldGuardBridge
version: 1.2.@BUILD@
depends: [WorldGuard]
author: [Kruithne, mortenn]
description: Bridge between Runsafe Framework and WorldGuard