name: RunsafeWorldGuardBridge
main: no.runsafe.worldguardbridge.WorldGuardBridge
version: 1.2.@BUILD@
depends: [WorldGuard, WorldEdit]
author: [Kruithne, mortenn]
description: Bridge between Runsafe Framework and WorldGuard
commands:
  rescanwgregions:
    description: Reload worldguard regions for region enter events
  updateRegionUUIDs:
    description: Updates regions to store playerIDs instead of usernames.